# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: ubuntu-latest
steps:
- script: dotnet restore
  workingDirectory: 'blok4/CASE.YL.WebApp'
  displayName: 'Restore'
- script: dotnet build
  workingDirectory: 'blok4/CASE.YL.WebApp'
  displayName: 'Build'
- script: dotnet test
  workingDirectory: 'blok4/CASE.YL.WebApp'
  displayName: 'Test'
