# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

variables:
- name: 'workingDir'
  value: 'blok4/CASE.YL.WebApp'

pool: 
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: dotnet restore
      workingDirectory: $(workingDir)
      displayName: 'Restore'
    - script: dotnet build
      workingDirectory: $(workingDir)
      displayName: 'Build'
    - script: dotnet test
      workingDirectory: $(workingDir)
      displayName: 'Test'
