version: '3'

services:
  app:
    build: 
      context: ./CASE.YL.WebApp
      dockerfile: Dockerfile
    ports:
      - 3000:80
    image: kcbdregistry.azurecr.io/yannick/cursus:latest
    environment:
      ConnectionStrings__CursusContext: 'Server=db; Database=dotnet7cursus; User=sa; Password=${DB_PASSWORD}; TrustServerCertificate=true;'
      Kestrel__Endpoints__Http__Url: 'http://+:80'
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y